version: '3.8'

services:
  db:
    image: postgres:13
    container_name: engstudybot_db
    environment:
      POSTGRES_DB: EngStudyBot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: engstudybot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  app:
    build: .
    container_name: engstudybot_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      DB_NAME: EngStudyBot
      DB_USER: postgres
      DB_PASSWORD: postgres
      TG_TOKEN: ${TG_TOKEN}
    volumes:
      - .:/app
      - audio_files:/app/eng_audio_files_mp3
    restart: unless-stopped

  test:
    build: .
    container_name: engstudybot_test
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      TEST_DB_NAME: TestEngStudyBot
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: ["python", "-m", "pytest", "tests/test.py", "-v"]
    volumes:
      - .:/app

volumes:
  postgres_data:
  audio_files:
  pgadmin_data:
