version: "3.8"

services:
  db:
    image: postgres:13
    container_name: engstudybot_db
    environment:
      POSTGRES_DB: ${DB_NAME:-EngStudyBot}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: engstudybot_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  app:
    build: .
    container_name: engstudybot_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: ${DB_HOST:-db}
      PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-EngStudyBot}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      TG_TOKEN: ${TG_TOKEN}
    volumes:
      - .:/app
      - audio_files:/app/eng_audio_files_mp3
    restart: unless-stopped

  test:
    build: .
    container_name: engstudybot_test
    depends_on:
      db:
        condition: service_healthy
    environment:
      HOST: ${DB_HOST:-db}
      PORT: ${DB_PORT:-5432}
      TEST_DB_NAME: ${TEST_DB_NAME:-TestEngStudyBot}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    command: ["python", "-m", "pytest", "tests/test.py", "-v"]
    volumes:
      - .:/app

volumes:
  postgres_data:
  audio_files:
  pgadmin_data:
